language: java
os:
  - windows
  - linux
  - osx
jdk:
  - openjdk8
  - oraclejdk8

matrix:
  include:
  - os: linux
    jdk: openjdk8
  - os: linux
    jdk: oraclejdk8
  allow_failures:
  - os: osx
    jdk: openjdk8
  - os: windows
    jdk: openjdk8

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
sudo: false
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
script: ./gradlew
after_success:
  - unzip -c build/libs/am-*.jar META-INF/MANIFEST.MF
